name = "institutional-school"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "dist"

[vars]
# TURSO_DATABASE_URL = ""
# TURSO_AUTH_TOKEN = ""

[[kv_namespaces]]
binding = "SESSION"
id = "772227ffd43f42fb9633e55bd9a4eb64"
